name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get-changed-files
        id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'

      - namme: Run Formatter
        run: |
          pip install --upgrade black
          readarray -t files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          for file in ${files[@]}; do
            if [[ ${file##*.} == "py" ]]; then
              black ${file}
            fi
          done
